//go:build !ignore_autogenerated

/*
Copyright kgpp34 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionPolicy) DeepCopyInto(out *AdmissionPolicy) {
	*out = *in
	out.MaxSnapshotAge = in.MaxSnapshotAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionPolicy.
func (in *AdmissionPolicy) DeepCopy() *AdmissionPolicy {
	if in == nil {
		return nil
	}
	out := new(AdmissionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationPolicy) DeepCopyInto(out *AllocationPolicy) {
	*out = *in
	if in.MinIncrease != nil {
		in, out := &in.MinIncrease, &out.MinIncrease
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	out.Cooldown = in.Cooldown
	out.FullResync = in.FullResync
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationPolicy.
func (in *AllocationPolicy) DeepCopy() *AllocationPolicy {
	if in == nil {
		return nil
	}
	out := new(AllocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicy) DeepCopyInto(out *CapacityPolicy) {
	*out = *in
	if in.Reserve != nil {
		in, out := &in.Reserve, &out.Reserve
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AdmissionRatio != nil {
		in, out := &in.AdmissionRatio, &out.AdmissionRatio
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.EntitlementRatio != nil {
		in, out := &in.EntitlementRatio, &out.EntitlementRatio
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicy.
func (in *CapacityPolicy) DeepCopy() *CapacityPolicy {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentPoolQuota) DeepCopyInto(out *DepartmentPoolQuota) {
	*out = *in
	if in.BaseQuota != nil {
		in, out := &in.BaseQuota, &out.BaseQuota
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxQuota != nil {
		in, out := &in.MaxQuota, &out.MaxQuota
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	out.ReclaimAfter = in.ReclaimAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentPoolQuota.
func (in *DepartmentPoolQuota) DeepCopy() *DepartmentPoolQuota {
	if in == nil {
		return nil
	}
	out := new(DepartmentPoolQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentPoolQuotaStatus) DeepCopyInto(out *DepartmentPoolQuotaStatus) {
	*out = *in
	if in.AllocatedLimits != nil {
		in, out := &in.AllocatedLimits, &out.AllocatedLimits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.EffectiveQuota != nil {
		in, out := &in.EffectiveQuota, &out.EffectiveQuota
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ObservedUsage != nil {
		in, out := &in.ObservedUsage, &out.ObservedUsage
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Borrowed != nil {
		in, out := &in.Borrowed, &out.Borrowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.LastDemandTime != nil {
		in, out := &in.LastDemandTime, &out.LastDemandTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentPoolQuotaStatus.
func (in *DepartmentPoolQuotaStatus) DeepCopy() *DepartmentPoolQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(DepartmentPoolQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentQuota) DeepCopyInto(out *DepartmentQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentQuota.
func (in *DepartmentQuota) DeepCopy() *DepartmentQuota {
	if in == nil {
		return nil
	}
	out := new(DepartmentQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DepartmentQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentQuotaList) DeepCopyInto(out *DepartmentQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DepartmentQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentQuotaList.
func (in *DepartmentQuotaList) DeepCopy() *DepartmentQuotaList {
	if in == nil {
		return nil
	}
	out := new(DepartmentQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DepartmentQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentQuotaSpec) DeepCopyInto(out *DepartmentQuotaSpec) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]DepartmentPoolQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentQuotaSpec.
func (in *DepartmentQuotaSpec) DeepCopy() *DepartmentQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(DepartmentQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentQuotaStatus) DeepCopyInto(out *DepartmentQuotaStatus) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]DepartmentPoolQuotaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentQuotaStatus.
func (in *DepartmentQuotaStatus) DeepCopy() *DepartmentQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(DepartmentQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticQuotaPolicy) DeepCopyInto(out *ElasticQuotaPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticQuotaPolicy.
func (in *ElasticQuotaPolicy) DeepCopy() *ElasticQuotaPolicy {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticQuotaPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticQuotaPolicyList) DeepCopyInto(out *ElasticQuotaPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticQuotaPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticQuotaPolicyList.
func (in *ElasticQuotaPolicyList) DeepCopy() *ElasticQuotaPolicyList {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticQuotaPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticQuotaPolicySpec) DeepCopyInto(out *ElasticQuotaPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]v1.ResourceName, len(*in))
		copy(*out, *in)
	}
	in.Allocation.DeepCopyInto(&out.Allocation)
	out.Pressure = in.Pressure
	out.Metrics = in.Metrics
	out.Eviction = in.Eviction
	out.Admission = in.Admission
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticQuotaPolicySpec.
func (in *ElasticQuotaPolicySpec) DeepCopy() *ElasticQuotaPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticQuotaPolicyStatus) DeepCopyInto(out *ElasticQuotaPolicyStatus) {
	*out = *in
	if in.LastCalculationTime != nil {
		in, out := &in.LastCalculationTime, &out.LastCalculationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticQuotaPolicyStatus.
func (in *ElasticQuotaPolicyStatus) DeepCopy() *ElasticQuotaPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionConfig) DeepCopyInto(out *EvictionConfig) {
	*out = *in
	out.SustainedFor = in.SustainedFor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionConfig.
func (in *EvictionConfig) DeepCopy() *EvictionConfig {
	if in == nil {
		return nil
	}
	out := new(EvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsPolicy) DeepCopyInto(out *MetricsPolicy) {
	*out = *in
	out.CollectionInterval = in.CollectionInterval
	out.MaxSampleAge = in.MaxSampleAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsPolicy.
func (in *MetricsPolicy) DeepCopy() *MetricsPolicy {
	if in == nil {
		return nil
	}
	out := new(MetricsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PressurePolicy) DeepCopyInto(out *PressurePolicy) {
	*out = *in
	out.RecoveryWindow = in.RecoveryWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PressurePolicy.
func (in *PressurePolicy) DeepCopy() *PressurePolicy {
	if in == nil {
		return nil
	}
	out := new(PressurePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePool) DeepCopyInto(out *ResourcePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePool.
func (in *ResourcePool) DeepCopy() *ResourcePool {
	if in == nil {
		return nil
	}
	out := new(ResourcePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourcePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePoolList) DeepCopyInto(out *ResourcePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourcePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePoolList.
func (in *ResourcePoolList) DeepCopy() *ResourcePoolList {
	if in == nil {
		return nil
	}
	out := new(ResourcePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourcePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePoolSpec) DeepCopyInto(out *ResourcePoolSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.CapacityPolicy.DeepCopyInto(&out.CapacityPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePoolSpec.
func (in *ResourcePoolSpec) DeepCopy() *ResourcePoolSpec {
	if in == nil {
		return nil
	}
	out := new(ResourcePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePoolStatus) DeepCopyInto(out *ResourcePoolStatus) {
	*out = *in
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AdmissionBudget != nil {
		in, out := &in.AdmissionBudget, &out.AdmissionBudget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ConfiguredEntitlementBudget != nil {
		in, out := &in.ConfiguredEntitlementBudget, &out.ConfiguredEntitlementBudget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.EffectiveEntitlementBudget != nil {
		in, out := &in.EffectiveEntitlementBudget, &out.EffectiveEntitlementBudget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AllocatedLimits != nil {
		in, out := &in.AllocatedLimits, &out.AllocatedLimits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePoolStatus.
func (in *ResourcePoolStatus) DeepCopy() *ResourcePoolStatus {
	if in == nil {
		return nil
	}
	out := new(ResourcePoolStatus)
	in.DeepCopyInto(out)
	return out
}
